# Generated by Django 4.2 on 2025-12-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors',
            name='price',
            field=models.IntegerField(default=12.5),
        ),
        migrations.AddField(
            model_name='tutors',
            name='subject',
            field=models.CharField(default='Chumash', max_length=254),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
