# Generated by Django 4.2 on 2025-12-23 10:21

from django.db import migrations, models
import tutors.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_tutors_price_tutors_subject_alter_tutors_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors',
            name='color_number',
            field=models.IntegerField(default=tutors.models.rand),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='subject',
            field=models.CharField(max_length=254),
        ),
    ]
