# Generated by Django 4.2 on 2025-12-23 12:25

from django.db import migrations, models
import tutors.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_tutors_color_number_alter_tutors_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutors',
            old_name='color_number',
            new_name='color_1',
        ),
        migrations.AddField(
            model_name='tutors',
            name='color_2',
            field=models.IntegerField(default=tutors.models.rand),
        ),
        migrations.AddField(
            model_name='tutors',
            name='color_3',
            field=models.IntegerField(default=tutors.models.rand),
        ),
    ]
