# Generated by Django 4.2 on 2025-12-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_rename_color_number_tutors_color_1_tutors_color_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutors',
            options={'verbose_name_plural': 'Tutors'},
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='reviews',
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tutors.tutors')),
            ],
            options={
                'verbose_name_plural': 'Reveiws',
            },
        ),
    ]
