# Generated by Django 4.2 on 2026-01-14 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutors', '0005_alter_tutors_options_remove_tutors_reviews_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
