# Generated by Django 4.2 on 2026-01-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_remove_message_user_message_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='tutor',
            new_name='tutor_name',
        ),
    ]
