# Generated by Django 4.2 on 2026-01-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_rename_tutor_message_tutor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='tutor_name',
        ),
        migrations.AddField(
            model_name='message',
            name='send_to',
            field=models.CharField(default='rebbegreen', max_length=254),
            preserve_default=False,
        ),
    ]
