# Generated by Django 4.2 on 2026-01-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_remove_message_tutor_name_message_send_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Default Subject', max_length=254),
            preserve_default=False,
        ),
    ]
